### ISSUE TITLE
ClassCircularityException when using JRTrace

### ISSUE THREAD

**Issue by ChristianPSchenk** [ChristianPSchenk/JRTrace#22]
I came across a classcirculartiy exception a few times when using JRTrace with regex=true. The threaddump below shows the problem: A class is being loaded, the transformer checks whether it "maymatch" (=is a candidate for injection). This requires the Pattern class and triggers the load of the Pattern class. This unfortunately is also passed into the transformation chain and causes the classcircularityexception.

Possible solutions:

- just ignore nested transformations
- prime classes required by jrtrace
- schedule nested transformations for later retransformations

=====

java.lang.ClassCircularityError: java/util/regex/Pattern$BnM
	at java.util.regex.Pattern.compile(Pattern.java:1709)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.util.regex.Pattern.matches(Pattern.java:1133)
	at java.lang.String.matches(String.java:2108)
	at de.schenk.jrtrace.helper.JRTraceClassMetadata.mayMatchClassName(JRTraceClassMetadata.java:223)
	at de.schenk.jrtrace.helper.JRTraceClassMetadata.mayMatchClassHierarchy(JRTraceClassMetadata.java:153)
	at de.schenk.jrtrace.helperagent.JRTraceClassFileTransformer.transform(JRTraceClassFileTransformer.java:86)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.util.regex.Pattern.compile(Pattern.java:1709)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.util.regex.Pattern.matches(Pattern.java:1133)
	at java.lang.String.matches(String.java:2108)
	at de.schenk.jrtrace.helper.JRTraceClassMetadata.mayMatchClassName(JRTraceClassMetadata.java:223)
	at de.schenk.jrtrace.helper.JRTraceClassMetadata.mayMatchClass(JRTraceClassMetadata.java:213)
	at de.schenk.jrtrace.helper.JRTraceClassMetadata.mayMatch(JRTraceClassMetadata.java:131)
	at de.schenk.jrtrace.helper.JRTraceHelper.potentialEngineXCandidate(JRTraceHelper.java:273)
	at de.schenk.jrtrace.helper.JRTraceHelper.addEngineXClass(JRTraceHelper.java:160)
	at de.schenk.jrtrace.helperagent.internal.InstallEngineXCommand.setEngineXClasses(InstallEngineXCommand.java:40)
	at de.schenk.jrtrace.helperagent.internal.InstallEngineXCommand.installEngineX(InstallEngineXCommand.java:28)
	at de.schenk.jrtrace.helperagent.internal.JRTraceMXBeanImpl.installEngineXClass(JRTraceMXBeanImpl.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by ChristianPSchenk** [comment]
The problem is that  the Pattern class has a lot of inner classes that might be triggered depending on the specific match. Therefore the only solution I see is to exclude the java.util.regex.Pattern classes from being instrumented for the case of regex=true.
