### ISSUE TITLE
ArrayIndexOutOfBoundsException from ASM when injecting @XReturn

### ISSUE THREAD

**Issue by ChristianPSchenk** [ChristianPSchenk/JRTrace#51]
Classis: org.eclipse.ui.internal.contexts.ContextService

JRTrace is:

  @XMethod(names = "activateContext", location = XLocation.AFTER_INVOCATION)
  public void traceActivation(@XReturn  Object activationContext) {
 ....
  }

Result is the below exception. 

Problem is misuse without proper error message:
- AFTER_INVOCATION should allow only @XInvokeReturn and immediately create an error
- unclear: currently the "_INVOCATION" locations picks even constructors (INVOKESPECIAL). Is there a proper error message in this case?

java.lang.ArrayIndexOutOfBoundsException: -1
	at de.schenk.objectweb.asm.Frame.merge(Frame.java:1311)
	at de.schenk.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1475)
	at de.schenk.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(LocalVariablesSorter.java:170)
	at de.schenk.objectweb.asm.tree.MethodNode.accept(MethodNode.java:835)
	at de.schenk.objectweb.asm.commons.JSRInlinerAdapter.visitEnd(JSRInlinerAdapter.java:187)
	at de.schenk.objectweb.asm.ClassReader.readMethod(ClassReader.java:1021)
	at de.schenk.objectweb.asm.ClassReader.accept(ClassReader.java:693)
	at de.schenk.objectweb.asm.ClassReader.accept(ClassReader.java:506)
	at de.schenk.jrtrace.helper.JRTraceOneClassTransformer.applyEngineXMethods(JRTraceOneClassTransformer.java:64)

**Comment by ChristianPSchenk** [comment]
Included checks to guard against the above misuse.
